# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  solution: '**/*.sln'
  projects: '**/*.csproj'
  nugetVersion: '5.2.0' # https://dist.nuget.org/tools.json

steps:
- task: UseDotNet@2
  displayName: 'Use dotnet sdk 2.x'
  inputs:
    version: 2.x
    includePreviewVersions: true

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: $(nugetVersion) 
    checkLatest: true

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: $(solution)
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: $(projects)
    arguments: '--configuration $(buildConfiguration)' 